server:
  port: 8082

spring:
  application:
    name: USER-SERVICE
  config:
    import: "optional:configserver:http://localhost:8083"

  # ✅ MongoDB Atlas Configuration
  data:
    mongodb:
      uri: mongodb+srv://namdevaniket446:Xoq0Cfsbu8yxPHs8@users.1fgfy.mongodb.net/?retryWrites=true&w=majority&appName=
      database: G1_Minde
      auto-index-creation: true
